export { About } from "./About";
export { Landingpage } from "./Landingpage";
export { Dashboard } from "./Dashboard";
export { Inbox } from "./Inbox";
export { OrderList } from "./OrderList";
export { Products } from "./Products";
export { Signup } from "./Signup";
export { Signin } from "./Signin";
export { ShopPage } from "./ShopPage";
export { CustomWoodPage } from "./CustomWoodPage";
export { AddToCart } from "./AddToCart";
export { UserProfile } from "./UserProfile";
export { CustomizedProduct } from "./CustomizedProduct";
export { AddNewProduct } from "./AddNewProduct";
export {UpdateProduct} from "./UpdateProduct"
export { MyAccount } from "./MyAccount";
export {ProductOptions} from "./ProductOptions";
export {HomepageImage} from "./HomepageImage";
export {HomepageProducts} from "./HomepageProducts";
export {OurValues} from "./OurValues";
export {OurAssortment} from "./OurAssortment";
export {WhyHoutTotaal} from "./WhyHoutTotaal";
export {TermsAndConditions} from "./TermsAndConditions";
export {AdminPrivacyPolicy} from "./AdminPrivacyPolicy";
export {AdminFAQ} from "./AdminFAQ";